import { AlertTriangle, ArrowLeft, ArrowRight, Check, ChevronDown } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { Alert, Button } from '../../components/UI'
import { api } from '../../services/api'
import type { Checklist, ChecklistItem, Trip } from '../../types'
import { formatKm } from '../../utils/format'

type Answer={status?:'OK'|'PROBLEMA';observacao:string}
export function ChecklistPage(){const {tripId}=useParams();const navigate=useNavigate();const[trip,setTrip]=useState<Trip>();const[items,setItems]=useState<ChecklistItem[]>([]);const[answers,setAnswers]=useState<Record<number,Answer>>({});const[result,setResult]=useState<Checklist>();const[error,setError]=useState('');const[loading,setLoading]=useState(false)
useEffect(()=>{Promise.all([api<Trip>(`/trips/${tripId}`),api<ChecklistItem[]>('/checklist-items')]).then(([t,i])=>{setTrip(t);setItems(i)}).catch(e=>setError(e.message))},[tripId])
const answered=Object.values(answers).filter(a=>a.status).length;const complete=items.filter(i=>i.obrigatorio).every(i=>answers[i.id]?.status);const progress=items.length?Math.round(answered/items.length*100):0
function update(id:number,patch:Partial<Answer>){setAnswers(current=>({...current,[id]:{...(current[id]||{observacao:''}),...patch}}))}
async function submit(){if(!complete){setError('Responda todos os itens obrigatórios.');return}setLoading(true);setError('');try{const payload=[];for(const item of items){const answer=answers[item.id];if(!answer?.status)continue;payload.push({checklist_item_id:item.id,status:answer.status,observacao:answer.observacao||null})}const checklist=await api<Checklist>(`/trips/${tripId}/checklist`,{method:'POST',body:JSON.stringify({answers:payload})});setResult(checklist)}catch(e){setError(e instanceof Error?e.message:'Erro ao salvar checklist')}finally{setLoading(false)}}
async function start(){setLoading(true);try{await api(`/trips/${tripId}/start`,{method:'POST'});navigate('/motorista',{replace:true})}catch(e){setError(e instanceof Error?e.message:'Erro ao iniciar viagem');setLoading(false)}}
if(result)return <div className="driver-page result-page fade-in"><p className="step-label">ETAPA 4 DE 4</p><div className={`result-icon ${result.status==='APROVADO'?'success':'warning'}`}>{result.status==='APROVADO'?<Check/>:<AlertTriangle/>}</div><p className="eyebrow">CHECKLIST CONCLUÍDO</p><h1>{result.status==='APROVADO'?'Veículo liberado':'Checklist com problemas'}</h1><p>{result.status==='APROVADO'?'Todos os itens foram verificados. Boa rota!':'Os problemas foram registrados. Você pode continuar neste MVP.'}</p><Button loading={loading} className="button--full button--xl" onClick={start}>Iniciar viagem <ArrowRight/></Button></div>
return <div className="driver-page checklist-page fade-in"><button className="back-link" onClick={()=>navigate(`/motorista/carga/${tripId}`)}><ArrowLeft/> Voltar</button><p className="step-label">ETAPA 3 DE 4</p><h1>Checklist de saída</h1><div className="checklist-meta"><strong>{trip?.vehicle_plate}</strong><span>{formatKm(trip?.km_inicial)}</span></div><p className="lead">Antes de sair, verifique todos os itens.</p><div className="progress"><span style={{width:`${progress}%`}}/><small>{answered} de {items.length}</small></div>{error&&<Alert>{error}</Alert>}<div className="checklist-list">{items.map((item,index)=>{const answer=answers[item.id]||{observacao:''};return <article className={`check-item ${answer.status?'answered':''}`} key={item.id}><div className="check-item-title"><span>{String(index+1).padStart(2,'0')}</span><h2>{item.nome}{item.obrigatorio&&<em>*</em>}</h2><ChevronDown/></div>{item.descricao&&<p>{item.descricao}</p>}<div className="answer-buttons"><button className={answer.status==='OK'?'selected ok':''} onClick={()=>update(item.id,{status:'OK',observacao:''})}><Check/> OK</button><button className={answer.status==='PROBLEMA'?'selected problem':''} onClick={()=>update(item.id,{status:'PROBLEMA'})}><AlertTriangle/> Problema</button></div>{answer.status==='PROBLEMA'&&<div className="problem-fields"><label>Descreva o problema<textarea value={answer.observacao} onChange={e=>update(item.id,{observacao:e.target.value})} placeholder="O que você encontrou?" required/></label></div>}</article>})}</div><div className="sticky-action"><Button loading={loading} disabled={!complete} className="button--full button--xl" onClick={submit}>Finalizar checklist <ArrowRight/></Button></div></div>}
