import { TrackingPage } from './pages/admin/TrackingPage'
import type { ReactNode } from 'react'
import { Navigate, Route, Routes } from 'react-router-dom'
import { useAuth } from './hooks/useAuth'
import { AdminLayout } from './layouts/AdminLayout'
import { DriverLayout } from './layouts/DriverLayout'
import { LoginPage } from './pages/LoginPage'
import { ChecklistSettingsPage } from './pages/admin/ChecklistSettingsPage'
import { DashboardPage } from './pages/admin/DashboardPage'
import { SettingsPage } from './pages/admin/SettingsPage'
import { DriversPage } from './pages/admin/DriversPage'
import { EntityDetailPage } from './pages/admin/EntityDetailPage'
import { OccurrencesPage } from './pages/admin/OccurrencesPage'
import { TripDetailPage } from './pages/admin/TripDetailPage'
import { TripsPage } from './pages/admin/TripsPage'
import { VehiclesPage } from './pages/admin/VehiclesPage'
import { ChecklistPage } from './pages/driver/ChecklistPage'
import { CargoPage } from './pages/driver/CargoPage'
import { DeliveryPage } from './pages/driver/DeliveryPage'
import { DriverHome } from './pages/driver/DriverHome'
import { FinishTripPage } from './pages/driver/FinishTripPage'
import { OccurrencePage } from './pages/driver/OccurrencePage'
import { StartTripPage } from './pages/driver/StartTripPage'

function Protected({role,children}:{role:'ADMIN'|'MOTORISTA';children:ReactNode}){const{user}=useAuth();if(!user)return <Navigate to="/login" replace/>;if(user.role!==role)return <Navigate to={user.role==='ADMIN'?'/admin':'/motorista'} replace/>;return children}
export default function App(){return <Routes><Route path="/login" element={<LoginPage/>}/><Route path="/motorista" element={<Protected role="MOTORISTA"><DriverLayout/></Protected>}><Route index element={<DriverHome/>}/><Route path="entrega/:tripId/:invoiceId" element={<DeliveryPage/>}/><Route path="iniciar" element={<StartTripPage/>}/><Route path="carga/:tripId" element={<CargoPage/>}/><Route path="checklist/:tripId" element={<ChecklistPage/>}/><Route path="ocorrencia" element={<OccurrencePage/>}/><Route path="finalizar" element={<FinishTripPage/>}/></Route><Route path="/admin" element={<Protected role="ADMIN"><AdminLayout/></Protected>}><Route index element={<DashboardPage/>}/><Route path="configuracoes" element={<SettingsPage/>}/><Route path="motoristas" element={<DriversPage/>}/><Route path="motoristas/:id" element={<EntityDetailPage kind="driver"/>}/><Route path="veiculos" element={<VehiclesPage/>}/><Route path="veiculos/:id" element={<EntityDetailPage kind="vehicle"/>}/><Route path="checklist" element={<ChecklistSettingsPage/>}/><Route path="viagens" element={<TripsPage/>}/><Route path="viagens/:id" element={<TripDetailPage/>}/><Route path="rastreamento" element={<TrackingPage/>}/><Route path="ocorrencias" element={<OccurrencesPage/>}/></Route><Route path="/rastreamento" element={<Navigate to="/admin/rastreamento" replace/>}/><Route path="*" element={<Navigate to="/login" replace/>}/></Routes>}
