import { ArrowDown, ArrowUp, Pencil, Plus, Power } from 'lucide-react'
import { useEffect, useState, type FormEvent } from 'react'
import { Alert, Button, Modal, StatusBadge } from '../../components/UI'
import { api } from '../../services/api'
import type { ChecklistItem } from '../../types'

const empty={nome:'',descricao:'',obrigatorio:true,ativo:true,ordem:1}
export function ChecklistSettingsPage(){const[items,setItems]=useState<ChecklistItem[]>([]);const[editing,setEditing]=useState<ChecklistItem>();const[form,setForm]=useState(empty);const[open,setOpen]=useState(false);const[error,setError]=useState('');const[loading,setLoading]=useState(false)
async function load(){try{setItems(await api<ChecklistItem[]>('/checklist-items?active_only=false'))}catch(e){setError((e as Error).message)}}useEffect(()=>{load()},[])
function show(item?:ChecklistItem){setEditing(item);setForm(item?{nome:item.nome,descricao:item.descricao||'',obrigatorio:item.obrigatorio,ativo:item.ativo,ordem:item.ordem}:{...empty,ordem:items.length+1});setOpen(true);setError('')}
async function save(e:FormEvent){e.preventDefault();setLoading(true);try{await api(editing?`/checklist-items/${editing.id}`:'/checklist-items',{method:editing?'PUT':'POST',body:JSON.stringify(form)});setOpen(false);load()}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
async function patch(item:ChecklistItem,data:Partial<ChecklistItem>){await api(`/checklist-items/${item.id}`,{method:'PUT',body:JSON.stringify(data)});load()}
return <div className="admin-page"><header className="page-heading"><div><p className="eyebrow">CONFIGURAÇÃO</p><h1>Checklist de saída</h1><p>Defina os itens exibidos ao motorista antes de cada viagem.</p></div><Button onClick={()=>show()}><Plus/> Novo item</Button></header>{error&&!open&&<Alert>{error}</Alert>}<section className="panel checklist-settings"><div className="settings-head"><span>Ordem</span><span>Item de verificação</span><span>Obrigatoriedade</span><span>Status</span><span/></div>{items.map((item,index)=><div className="settings-row" key={item.id}><div className="order-controls"><button disabled={index===0} onClick={()=>patch(item,{ordem:Math.max(0,item.ordem-1)})}><ArrowUp/></button><b>{item.ordem}</b><button disabled={index===items.length-1} onClick={()=>patch(item,{ordem:item.ordem+1})}><ArrowDown/></button></div><div><strong>{item.nome}</strong><small>{item.descricao||'Sem descrição adicional'}</small></div><span>{item.obrigatorio?'Obrigatório':'Opcional'}</span><StatusBadge value={item.ativo?'ATIVO':'INATIVO'}/><div className="row-actions"><button onClick={()=>show(item)}><Pencil/></button><button onClick={()=>patch(item,{ativo:!item.ativo})}><Power/></button></div></div>)}</section>
<Modal open={open} title={editing?'Editar item':'Novo item'} onClose={()=>setOpen(false)}>{error&&<Alert>{error}</Alert>}<form className="modal-form" onSubmit={save}><label>Nome<input value={form.nome} onChange={e=>setForm({...form,nome:e.target.value})} required/></label><label>Descrição<textarea value={form.descricao} onChange={e=>setForm({...form,descricao:e.target.value})}/></label><label>Ordem<input type="number" min="0" value={form.ordem} onChange={e=>setForm({...form,ordem:Number(e.target.value)})}/></label><label className="switch"><input type="checkbox" checked={form.obrigatorio} onChange={e=>setForm({...form,obrigatorio:e.target.checked})}/><span/>Item obrigatório</label><label className="switch"><input type="checkbox" checked={form.ativo} onChange={e=>setForm({...form,ativo:e.target.checked})}/><span/>Item ativo</label><footer><Button type="button" variant="ghost" onClick={()=>setOpen(false)}>Cancelar</Button><Button type="submit" loading={loading}>Salvar item</Button></footer></form></Modal></div>}

