import { CalendarDays, CheckCircle2, ClipboardCheck, Gauge, Route, TriangleAlert, Truck } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Alert, StatusBadge } from '../../components/UI'
import { api } from '../../services/api'
import type { Dashboard, Driver, OccurrenceType, Page, Vehicle } from '../../types'
import { formatDate, formatKm, labelEnum } from '../../utils/format'

const periods={today:'Hoje',week:'Esta semana',month:'Este mês',30:'Últimos 30 dias',all:'Todo o histórico'}
function dateFrom(period:string){const d=new Date();if(period==='today')d.setHours(0,0,0,0);else if(period==='week'){d.setDate(d.getDate()-d.getDay()+1);d.setHours(0,0,0,0)}else if(period==='month'){d.setDate(1);d.setHours(0,0,0,0)}else if(period==='30')d.setDate(d.getDate()-30);else return '';return d.toISOString()}

export function DashboardPage(){const navigate=useNavigate();const[data,setData]=useState<Dashboard>();const[drivers,setDrivers]=useState<Driver[]>([]);const[vehicles,setVehicles]=useState<Vehicle[]>([]);const[period,setPeriod]=useState('month');const[driver,setDriver]=useState('');const[vehicle,setVehicle]=useState('');const[type,setType]=useState<OccurrenceType|''>('');const[error,setError]=useState('')
useEffect(()=>{Promise.all([api<Page<Driver>>('/drivers?page_size=100'),api<Page<Vehicle>>('/vehicles?page_size=100')]).then(([d,v])=>{setDrivers(d.items);setVehicles(v.items)})},[])
useEffect(()=>{const params=new URLSearchParams();const from=dateFrom(period);if(from)params.set('date_from',from);if(driver)params.set('driver_id',driver);if(vehicle)params.set('vehicle_id',vehicle);if(type)params.set('occurrence_type',type);api<Dashboard>(`/dashboard?${params}`).then(setData).catch(e=>setError(e.message))},[period,driver,vehicle,type])
const maxCheck=Math.max(1,...(data?.checklist_series.map(x=>x.total)||[]));const maxType=Math.max(1,...(data?.occurrence_by_type.map(x=>x.total)||[]));
if(!data&&!error)return <div className="loading-page">Consolidando indicadores…</div>
return <div className="admin-page fade-in"><header className="page-heading"><div><p className="eyebrow">CENTRAL OPERACIONAL</p><h1>Visão geral da frota</h1><p>Acompanhe o que está em movimento e o que precisa de atenção.</p></div><span className="date-chip"><CalendarDays/> Atualizado agora</span></header>{error&&<Alert>{error}</Alert>}
<section className="filter-bar" aria-label="Filtros"><label>Período<select value={period} onChange={e=>setPeriod(e.target.value)}>{Object.entries(periods).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Motorista<select value={driver} onChange={e=>setDriver(e.target.value)}><option value="">Todos</option>{drivers.map(d=><option key={d.id} value={d.id}>{d.nome}</option>)}</select></label><label>Veículo<select value={vehicle} onChange={e=>setVehicle(e.target.value)}><option value="">Todos</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.placa}</option>)}</select></label><label>Tipo de ocorrência<select value={type} onChange={e=>setType(e.target.value as OccurrenceType|'')}><option value="">Todos</option>{['ACIDENTE','AVARIA','PROBLEMA_MECANICO','PROBLEMA_ELETRICO','PNEU','PROBLEMA_ENTREGA','CLIENTE_AUSENTE','ATRASO','MULTA','ABASTECIMENTO','OUTRO'].map(t=><option value={t} key={t}>{labelEnum(t)}</option>)}</select></label></section>
<section className="metric-grid"><Metric icon={<Truck/>} label="Veículos" value={data?.total_vehicles||0}/><Metric icon={<Route/>} label="Viagens" value={data?.total_trips||0}/><Metric icon={<ClipboardCheck/>} label="Checklists" value={data?.total_checklists||0}/><Metric icon={<TriangleAlert/>} label="Ocorrências" value={data?.total_occurrences||0} alert={!!data?.open_occurrences}/><Metric icon={<Gauge/>} label="KM percorridos" value={formatKm(data?.total_km)} wide/></section>
<section className="panel table-panel"><h2>Entregas por rota</h2><p>Até 100 rotas mais recentes do período.</p><div className="table-wrap"><table><thead><tr><th>Rota</th><th>Motorista</th><th>Total</th><th>Entregues</th><th>Não entregues / ocorrências</th><th>Pendentes</th><th>Última entrega</th></tr></thead><tbody>{data?.delivery_routes.map(r=><tr key={r.id}><td><a href={`/admin/viagens/${r.id}`}>#{r.id}</a></td><td>{r.driver_name}</td><td>{r.total}</td><td>{r.delivered}</td><td>{r.failed}</td><td>{r.pending}</td><td>{formatDate(r.last_delivered_at)}</td></tr>)}</tbody></table></div></section><div className="dashboard-grid"><section className="panel fleet-panel"><PanelTitle title="Status da frota" subtitle="Situação atual dos veículos"/><div className="fleet-status"><StatusCount color="green" value={data?.available_vehicles||0} label="Disponíveis"/><StatusCount color="blue" value={data?.vehicles_in_trip||0} label="Em viagem"/><StatusCount color="orange" value={data?.vehicles_attention||0} label="Com atenção"/><StatusCount color="gray" value={data?.inactive_vehicles||0} label="Inativos"/></div></section>
<section className="panel"><PanelTitle title="Checklists" subtitle="Volume do período"/><div className="mini-stats"><span>Hoje<strong>{data?.checklists_today}</strong></span><span>Semana<strong>{data?.checklists_this_week}</strong></span><span>Mês<strong>{data?.checklists_this_month}</strong></span><span>Problemas<strong>{data?.checklists_with_problems}</strong></span></div><div className="bar-chart" aria-label="Gráfico de checklists">{data?.checklist_series.slice(-10).map(x=><div key={x.date} title={`${x.date}: ${x.total}`}><span style={{height:`${Math.max(8,x.total/maxCheck*100)}%`}}/><small>{new Date(`${x.date}T12:00:00`).toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'})}</small></div>)}</div></section>
<section className="panel"><PanelTitle title="Ocorrências" subtitle="Distribuição por tipo"/><div className="occurrence-summary"><span><b>{data?.total_occurrences}</b>Total</span><span><b>{data?.open_occurrences}</b>Abertas</span><span><b>{data?.in_analysis_occurrences}</b>Em análise</span><span><b>{data?.resolved_occurrences}</b>Resolvidas</span></div><div className="horizontal-chart">{data?.occurrence_by_type.map(x=><div key={x.type}><label>{labelEnum(x.type)} <b>{x.total}</b></label><span><i style={{width:`${x.total/maxType*100}%`}}/></span></div>)}</div></section></div>
<section className="panel table-panel"><PanelTitle title="Motoristas" subtitle="Histórico operacional no período"/><div className="table-wrap"><table><thead><tr><th>Motorista</th><th>Viagens</th><th>Checklists</th><th>Ocorrências</th><th>KM</th></tr></thead><tbody>{data?.drivers.map(d=><tr key={d.id} onClick={()=>navigate(`/admin/motoristas/${d.id}`)} tabIndex={0}><td><strong>{d.name}</strong></td><td>{d.trips}</td><td>{d.checklists}</td><td>{d.occurrences}</td><td>{formatKm(d.km)}</td></tr>)}</tbody></table></div></section>
<section className="panel table-panel"><PanelTitle title="Veículos" subtitle="Utilização e situação atual"/><div className="table-wrap"><table><thead><tr><th>Placa</th><th>Modelo</th><th>Status</th><th>KM atual</th><th>Viagens</th><th>Ocorrências</th></tr></thead><tbody>{data?.vehicles.map(v=><tr key={v.id} onClick={()=>navigate(`/admin/veiculos/${v.id}`)} tabIndex={0}><td><strong className="mono">{v.plate}</strong></td><td>{v.model}</td><td><StatusBadge value={v.status}/></td><td>{formatKm(v.km)}</td><td>{v.trips}</td><td>{v.occurrences}</td></tr>)}</tbody></table></div></section></div>}
function Metric({icon,label,value,alert,wide}:{icon:React.ReactNode;label:string;value:string|number;alert?:boolean;wide?:boolean}){return <article className={`metric-card ${alert?'metric-card--alert':''} ${wide?'metric-card--wide':''}`}><span>{icon}</span><div><small>{label}</small><strong>{value}</strong></div></article>}
function PanelTitle({title,subtitle}:{title:string;subtitle:string}){return <header className="panel-title"><div><h2>{title}</h2><p>{subtitle}</p></div></header>}
function StatusCount({color,value,label}:{color:string;value:number;label:string}){return <div><i className={`dot dot--${color}`}/><strong>{value}</strong><span>{label}</span></div>}

