import { Pencil, Plus, Power } from 'lucide-react'
import { useEffect, useState, type FormEvent } from 'react'
import { useNavigate } from 'react-router-dom'
import { Alert, Button, Empty, Modal, StatusBadge } from '../../components/UI'
import { api } from '../../services/api'
import type { Driver, Page } from '../../types'
import { formatCpf } from '../../utils/format'

const empty={nome:'',email:'',senha:''}
export function DriversPage(){const navigate=useNavigate();const[items,setItems]=useState<Driver[]>([]);const[editing,setEditing]=useState<Driver>();const[open,setOpen]=useState(false);const[form,setForm]=useState(empty);const[error,setError]=useState('');const[loading,setLoading]=useState(false)
async function load(){try{setItems((await api<Page<Driver>>('/drivers?page_size=100')).items)}catch(e){setError((e as Error).message)}}useEffect(()=>{load()},[])
function show(item?:Driver){setEditing(item);setForm(item?{nome:item.nome,email:item.email||'',senha:''}:empty);setOpen(true);setError('')}
async function save(e:FormEvent){e.preventDefault();setLoading(true);setError('');const body={...form,...(!form.senha&&editing?{senha:undefined}:{})};try{await api(editing?`/drivers/${editing.id}`:'/drivers',{method:editing?'PUT':'POST',body:JSON.stringify(body)});setOpen(false);load()}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
async function toggle(item:Driver){await api(`/drivers/${item.id}/status`,{method:'PATCH',body:JSON.stringify({ativo:!item.ativo})});load()}
return <div className="admin-page"><header className="page-heading"><div><p className="eyebrow">CADASTROS</p><h1>Motoristas</h1><p>Usuários habilitados para registrar as operações da frota.</p></div><Button onClick={()=>show()}><Plus/> Novo motorista</Button></header>{error&&!open&&<Alert>{error}</Alert>}<section className="panel table-panel">{items.length?<div className="table-wrap"><table><thead><tr><th>Motorista</th><th>CPF</th><th>Telefone</th><th>E-mail</th><th>Status</th><th aria-label="Ações"/></tr></thead><tbody>{items.map(item=><tr key={item.id}><td><button className="table-link" onClick={()=>navigate(`/admin/motoristas/${item.id}`)}>{item.nome}</button></td><td>{formatCpf(item.cpf)}</td><td>{item.telefone}</td><td>{item.email}</td><td><StatusBadge value={item.ativo?'ATIVO':'INATIVO'}/></td><td className="row-actions"><button onClick={()=>show(item)} aria-label={`Editar ${item.nome}`}><Pencil/></button><button onClick={()=>toggle(item)} aria-label={item.ativo?'Desativar':'Ativar'}><Power/></button></td></tr>)}</tbody></table></div>:<Empty title="Nenhum motorista" description="Cadastre o primeiro motorista para iniciar a operação."/>}</section>
<Modal open={open} onClose={()=>setOpen(false)} title={editing?'Editar motorista':'Novo motorista'}>{error&&<Alert>{error}</Alert>}<form className="modal-form" onSubmit={save}><label>Nome<input value={form.nome} onChange={e=>setForm({...form,nome:e.target.value})} required/></label><label>E-mail<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></label><label>Senha {editing&&<small>(deixe em branco para manter)</small>}<input type="password" value={form.senha} onChange={e=>setForm({...form,senha:e.target.value})} required={!editing} minLength={8}/></label><footer><Button type="button" variant="ghost" onClick={()=>setOpen(false)}>Cancelar</Button><Button type="submit" loading={loading}>Salvar motorista</Button></footer></form></Modal></div>}

