import { ArrowLeft, ClipboardCheck, Gauge, Route, TriangleAlert } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { Alert, StatusBadge } from '../../components/UI'
import { api } from '../../services/api'
import type { Dashboard, Driver, Page, Trip, Vehicle } from '../../types'
import { formatDate, formatKm } from '../../utils/format'

export function EntityDetailPage({kind}:{kind:'driver'|'vehicle'}){const{id}=useParams();const navigate=useNavigate();const[entity,setEntity]=useState<Driver|Vehicle>();const[trips,setTrips]=useState<Trip[]>([]);const[stats,setStats]=useState<Dashboard>();const[error,setError]=useState('')
useEffect(()=>{const key=kind==='driver'?'driver_id':'vehicle_id';Promise.all([api<Driver|Vehicle>(`/${kind==='driver'?'drivers':'vehicles'}/${id}`),api<Page<Trip>>(`/trips?${key}=${id}&page_size=100`),api<Dashboard>(`/dashboard?${key}=${id}`)]).then(([e,t,s])=>{setEntity(e);setTrips(t.items);setStats(s)}).catch(e=>setError(e.message))},[id,kind]);const isDriver=kind==='driver';const driver=entity as Driver;const vehicle=entity as Vehicle;const row=isDriver?stats?.drivers[0]:stats?.vehicles[0]
return <div className="admin-page"><button className="back-link" onClick={()=>navigate(-1)}><ArrowLeft/> Voltar</button>{error&&<Alert>{error}</Alert>}<header className="page-heading"><div><p className="eyebrow">{isDriver?'MOTORISTA':'VEÍCULO'}</p><h1>{isDriver?driver?.nome:vehicle?.placa}</h1><p>{isDriver?driver?.email:`${vehicle?.marca||''} ${vehicle?.modelo||''}`}</p></div>{entity&&<StatusBadge value={isDriver?(driver.ativo?'ATIVO':'INATIVO'):vehicle.status}/>}</header><section className="detail-metrics"><article><Route/><span>Viagens<strong>{row?.trips||0}</strong></span></article><article><ClipboardCheck/><span>Checklists<strong>{isDriver?(row as Dashboard['drivers'][number])?.checklists||0:row?.trips||0}</strong></span></article><article><TriangleAlert/><span>Ocorrências<strong>{row?.occurrences||0}</strong></span></article><article><Gauge/><span>{isDriver?'KM percorridos':'KM atual'}<strong>{formatKm(isDriver?(row as Dashboard['drivers'][number])?.km:vehicle?.km_atual)}</strong></span></article></section><section className="panel table-panel"><h2>Histórico de viagens</h2><div className="table-wrap"><table><thead><tr><th>Saída</th>{!isDriver&&<th>Motorista</th>} {isDriver&&<th>Veículo</th>}<th>KM percorrido</th><th>Ocorrências</th><th>Status</th></tr></thead><tbody>{trips.map(t=><tr key={t.id} onClick={()=>navigate(`/admin/viagens/${t.id}`)}><td>{formatDate(t.data_saida)}</td><td>{isDriver?t.vehicle_plate:t.driver_name}</td><td>{formatKm(t.km_percorrido)}</td><td>{t.occurrence_count}</td><td><StatusBadge value={t.status}/></td></tr>)}</tbody></table></div></section></div>}

