import { Search } from 'lucide-react'
import { useEffect, useState, type FormEvent } from 'react'
import { Alert, Button, Empty, Modal, StatusBadge } from '../../components/UI'
import { api } from '../../services/api'
import type { Occurrence, OccurrenceStatus, Page } from '../../types'
import { formatDate, labelEnum } from '../../utils/format'

export function OccurrencesPage(){const[data,setData]=useState<Page<Occurrence>>();const[filter,setFilter]=useState<OccurrenceStatus|''>('');const[selected,setSelected]=useState<Occurrence>();const[status,setStatus]=useState<OccurrenceStatus>('ABERTA');const[note,setNote]=useState('');const[error,setError]=useState('');const[loading,setLoading]=useState(false)
async function load(){try{setData(await api<Page<Occurrence>>(`/occurrences?page_size=100${filter?`&status=${filter}`:''}`))}catch(e){setError((e as Error).message)}}useEffect(()=>{load()},[filter]);function open(item:Occurrence){setSelected(item);setStatus(item.status);setNote(item.observacao_gestor||'');setError('')}
async function save(e:FormEvent){e.preventDefault();setLoading(true);try{await api(`/occurrences/${selected?.id}`,{method:'PATCH',body:JSON.stringify({status,observacao_gestor:note||null})});setSelected(undefined);load()}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
return <div className="admin-page"><header className="page-heading"><div><p className="eyebrow">ACOMPANHAMENTO</p><h1>Ocorrências</h1><p>Registros enviados durante as rotas e seu tratamento.</p></div></header>{error&&!selected&&<Alert>{error}</Alert>}<section className="filter-bar filter-bar--compact"><label>Status<select value={filter} onChange={e=>setFilter(e.target.value as OccurrenceStatus|'')}><option value="">Todos</option><option value="ABERTA">Aberta</option><option value="EM_ANALISE">Em análise</option><option value="RESOLVIDA">Resolvida</option><option value="CANCELADA">Cancelada</option></select></label><span className="result-count"><Search/> {data?.total||0} registros</span></section><section className="panel table-panel">{data?.items.length?<div className="table-wrap"><table><thead><tr><th>Data</th><th>Motorista</th><th>Veículo</th><th>Tipo</th><th>Descrição</th><th>Status</th></tr></thead><tbody>{data.items.map(o=><tr key={o.id} onClick={()=>open(o)} tabIndex={0}><td>{formatDate(o.data_hora)}</td><td><strong>{o.driver_name}</strong></td><td className="mono">{o.vehicle_plate}</td><td>{labelEnum(o.tipo)}</td><td className="truncate">{o.descricao}</td><td><StatusBadge value={o.status}/></td></tr>)}</tbody></table></div>:<Empty title="Nenhuma ocorrência" description="Não há registros para o filtro selecionado."/>}</section><Modal open={!!selected} onClose={()=>setSelected(undefined)} title={`Ocorrência #${String(selected?.id||0).padStart(6,'0')}`}>{error&&<Alert>{error}</Alert>}{selected&&<form className="occurrence-detail modal-form" onSubmit={save}><dl><div><dt>Data</dt><dd>{formatDate(selected.data_hora)}</dd></div><div><dt>Motorista</dt><dd>{selected.driver_name}</dd></div><div><dt>Veículo</dt><dd>{selected.vehicle_plate}</dd></div><div><dt>Viagem</dt><dd>#{selected.trip_id}</dd></div><div><dt>Tipo</dt><dd>{labelEnum(selected.tipo)}</dd></div><div className="full"><dt>Descrição</dt><dd>{selected.descricao}</dd></div><div className="full"><dt>Local</dt><dd>{selected.local||'Não informado'}</dd></div></dl><label>Status<select value={status} onChange={e=>setStatus(e.target.value as OccurrenceStatus)}><option value="ABERTA">Aberta</option><option value="EM_ANALISE">Em análise</option><option value="RESOLVIDA">Resolvida</option><option value="CANCELADA">Cancelada</option></select></label><label>Observação do gestor<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Registre o andamento da tratativa"/></label><footer><Button type="button" variant="ghost" onClick={()=>setSelected(undefined)}>Cancelar</Button><Button type="submit" loading={loading}>Salvar</Button></footer></form>}</Modal></div>}

