import { DeliveryRoute } from '../../components/DeliveryRoute'
import { ArrowLeft, Boxes, ClipboardCheck, FileText, TriangleAlert } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { Alert, Button, Modal, StatusBadge } from '../../components/UI'
import { api } from '../../services/api'
import type { Checklist, Page, Occurrence, Trip } from '../../types'
import { formatDate, formatKm } from '../../utils/format'

export function TripDetailPage(){const{id}=useParams();const navigate=useNavigate();const[trip,setTrip]=useState<Trip>();const[checklist,setChecklist]=useState<Checklist>();const[occurrences,setOccurrences]=useState<Occurrence[]>([]);const[showChecklist,setShowChecklist]=useState(false);const[error,setError]=useState('')
useEffect(()=>{api<Trip>(`/trips/${id}`).then(t=>{setTrip(t);if(t.checklist_id)api<Checklist>(`/checklists/${t.checklist_id}`).then(setChecklist);api<Page<Occurrence>>(`/occurrences?trip_id=${t.id}&page_size=100`).then(r=>setOccurrences(r.items))}).catch(e=>setError(e.message))},[id])
return <div className="admin-page"><button className="back-link" onClick={()=>navigate(-1)}><ArrowLeft/> Voltar</button>{error&&<Alert>{error}</Alert>}<header className="page-heading"><div><p className="eyebrow">VIAGEM #{String(trip?.id||0).padStart(5,'0')}</p><h1>{trip?.vehicle_plate}</h1><p>{trip?.driver_name}</p></div>{trip&&<StatusBadge value={trip.status}/>}</header><section className="detail-grid"><article className="panel detail-hero"><div><small>Motorista</small><strong>{trip?.driver_name}</strong></div><div><small>Veículo</small><strong>{trip?.vehicle_plate}</strong></div><div><small>Saída</small><strong>{formatDate(trip?.data_saida)}</strong></div><div><small>Retorno</small><strong>{formatDate(trip?.data_retorno)}</strong></div></article><article className="panel odometer"><small>Quilometragem</small><div><span>{formatKm(trip?.km_inicial)}<small>inicial</small></span><i>→</i><span>{trip?.km_final?formatKm(trip.km_final):'—'}<small>final</small></span></div><strong>{formatKm(trip?.km_percorrido)} percorridos</strong></article></section><section className="panel cargo-detail"><div className="panel-title"><div><h2><FileText/> Notas e volumes</h2><p>Carga informada pelo motorista antes da saída.</p></div><strong><Boxes/> {trip?.total_volumes||0} volumes</strong></div>{trip?.notas.length?<div className="cargo-note-grid">{trip.notas.map(nota=><div key={nota.id}><span>Nota {nota.numero_nota}</span><strong>{nota.volumes} {nota.volumes===1?'volume':'volumes'}</strong></div>)}</div>:<p className="muted">Nenhuma nota informada.</p>}</section>{trip&&<DeliveryRoute trip={trip} admin/>}<section className="detail-actions"><Button variant="secondary" disabled={!checklist} onClick={()=>setShowChecklist(true)}><ClipboardCheck/> Ver checklist</Button><Button variant="secondary" onClick={()=>document.getElementById('trip-occurrences')?.scrollIntoView()}><TriangleAlert/> Ver ocorrências ({occurrences.length})</Button></section><section id="trip-occurrences" className="panel table-panel"><h2>Ocorrências</h2>{occurrences.length?<div className="table-wrap"><table><thead><tr><th>Data</th><th>Tipo</th><th>Descrição</th><th>Status</th></tr></thead><tbody>{occurrences.map(o=><tr key={o.id}><td>{formatDate(o.data_hora)}</td><td>{o.tipo}</td><td>{o.descricao}</td><td><StatusBadge value={o.status}/></td></tr>)}</tbody></table></div>:<p className="muted">Nenhuma ocorrência nesta viagem.</p>}</section><Modal open={showChecklist} onClose={()=>setShowChecklist(false)} title="Checklist da viagem">{checklist&&<div className="checklist-detail"><StatusBadge value={checklist.status}/>{checklist.answers.map(a=><div key={a.id}><span>{a.item.nome}</span><StatusBadge value={a.status}/>{a.observacao&&<small>{a.observacao}</small>}</div>)}</div>}</Modal></div>}
