import { Pencil, Plus, Power } from 'lucide-react'
import { useEffect, useState, type FormEvent } from 'react'
import { useNavigate } from 'react-router-dom'
import { Alert, Button, Empty, Modal, StatusBadge } from '../../components/UI'
import { api } from '../../services/api'
import type { Page, Vehicle, VehicleStatus } from '../../types'
import { formatKm } from '../../utils/format'

const empty={placa:'',marca:'',modelo:'',tipo:'',km_atual:0,status:'DISPONIVEL' as VehicleStatus,ativo:true}
export function VehiclesPage(){const navigate=useNavigate();const[items,setItems]=useState<Vehicle[]>([]);const[editing,setEditing]=useState<Vehicle>();const[open,setOpen]=useState(false);const[form,setForm]=useState(empty);const[error,setError]=useState('');const[loading,setLoading]=useState(false)
async function load(){try{setItems((await api<Page<Vehicle>>('/vehicles?page_size=100')).items)}catch(e){setError((e as Error).message)}}useEffect(()=>{load()},[])
function show(item?:Vehicle){setEditing(item);setForm(item?{placa:item.placa,marca:item.marca,modelo:item.modelo,tipo:item.tipo,km_atual:item.km_atual,status:item.status,ativo:item.ativo}:empty);setOpen(true);setError('')}
async function save(e:FormEvent){e.preventDefault();setLoading(true);setError('');try{await api(editing?`/vehicles/${editing.id}`:'/vehicles',{method:editing?'PUT':'POST',body:JSON.stringify(form)});setOpen(false);load()}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
async function toggle(item:Vehicle){try{await api(`/vehicles/${item.id}/status`,{method:'PATCH',body:JSON.stringify({ativo:!item.ativo})});load()}catch(e){setError((e as Error).message)}}
return <div className="admin-page"><header className="page-heading"><div><p className="eyebrow">CADASTROS</p><h1>Veículos</h1><p>Disponibilidade, quilometragem e histórico da frota.</p></div><Button onClick={()=>show()}><Plus/> Novo veículo</Button></header>{error&&!open&&<Alert>{error}</Alert>}<section className="panel table-panel">{items.length?<div className="table-wrap"><table><thead><tr><th>Placa</th><th>Veículo</th><th>Tipo</th><th>KM atual</th><th>Status</th><th aria-label="Ações"/></tr></thead><tbody>{items.map(item=><tr key={item.id}><td><button className="table-link mono" onClick={()=>navigate(`/admin/veiculos/${item.id}`)}>{item.placa}</button></td><td>{item.marca} {item.modelo}</td><td>{item.tipo}</td><td>{formatKm(item.km_atual)}</td><td><StatusBadge value={item.status}/></td><td className="row-actions"><button onClick={()=>show(item)}><Pencil/></button><button onClick={()=>toggle(item)}><Power/></button></td></tr>)}</tbody></table></div>:<Empty title="Nenhum veículo" description="Cadastre o primeiro veículo da frota."/>}</section>
<Modal open={open} onClose={()=>setOpen(false)} title={editing?'Editar veículo':'Novo veículo'}>{error&&<Alert>{error}</Alert>}<form className="modal-form" onSubmit={save}><div className="form-row"><label>Placa<input value={form.placa} onChange={e=>setForm({...form,placa:e.target.value.toUpperCase()})} required/></label><label>Marca<input value={form.marca} onChange={e=>setForm({...form,marca:e.target.value})} required/></label></div><label>Modelo<input value={form.modelo} onChange={e=>setForm({...form,modelo:e.target.value})} required/></label><div className="form-row"><label>Tipo<input value={form.tipo} onChange={e=>setForm({...form,tipo:e.target.value})} required/></label><label>KM atual<input type="number" min="0" value={form.km_atual} onChange={e=>setForm({...form,km_atual:Number(e.target.value)})} required/></label></div><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as VehicleStatus})}><option value="DISPONIVEL">Disponível</option><option value="ATENCAO">Atenção</option><option value="INATIVO">Inativo</option>{editing?.status==='EM_VIAGEM'&&<option value="EM_VIAGEM">Em viagem</option>}</select></label><label className="switch"><input type="checkbox" checked={form.ativo} onChange={e=>setForm({...form,ativo:e.target.checked})}/><span/>Veículo ativo</label><footer><Button type="button" variant="ghost" onClick={()=>setOpen(false)}>Cancelar</Button><Button type="submit" loading={loading}>Salvar veículo</Button></footer></form></Modal></div>}

